name: Build Release APK

on:
  workflow_dispatch:   # lets you trigger it manually
  push:
    branches:
      - main           # also runs on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'   # or pin exact version, e.g. '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: savera-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
