name: Build Release APK

on:
  push:
    branches:
      - main      # or whatever your branch is
  workflow_dispatch:  # allows manual trigger too

jobs:
  build_android:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # or specify version like '3.10.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: |
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: savera-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
