name: Build Release APK - 2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'      # specify exact stable version
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: savera-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
